server:
  port: 19093
  undertow:
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理 每块buffer的空间大小,越小的空间被利用越充分，不要设置太大，以免影响其他应用，合适即可
    buffer-size: 1024
    # 是否分配的直接内存(NIO直接分配的堆外内存)
    direct-buffers: true
    threads:
      worker: 64 # 阻塞任务线程池, 当执行类似servlet请求阻塞IO操作, undertow会从这个线程池中取得线程 它的值设置取决于系统线程执行任务的阻塞系数，默认值是IO线程数*8
      io: 8 #设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程 不要设置过大，如果过大，启动项目会报错：打开文件数过多

eureka:
  client:
    serviceUrl: #注册中心的注册地址
      defaultZone: http://localhost:8090/eureka/
    registry-fetch-interval-seconds: 5 #指示从eureka获取注册表信息的频率(以秒为单位)
    register-with-eureka: true
    fetch-registry: true
  instance:
    #    instance-id: ${spring.application.instance_id:${random.value}}:${spring.application.name}:${server.port}
    prefer-ip-address: true # 就把ip注册到eureka了，不加的话我看过eureka注册界面，是以docker容器的container id注册过去的
    lease-renewal-interval-in-seconds: 3 #表示eureka客户端发送心跳的频率(以秒为单位)
    lease-expiration-duration-in-seconds: 5  # 过期时间，默认90s, 可不配置

feign:  # feign默认的连接时长10s和读取时长60s不生效,重新指定 https://blog.csdn.net/weixin_42241455/article/details/121871337
  client:
    config:
      default:
        #不设置connectTimeout会导致readTimeout设置不生效
        connectTimeout: 10000
        readTimeout: 60000

spring:
  application:
    name: gn-api
  main:
    allow-bean-definition-overriding: true # 意思是后来发现的bean会覆盖之前相同名称的bean

  datasource:
    url: jdbc:mysql://106.75.115.170:3306/gn-web?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: root
    password: gwk_632697105qq
    druid:
      initial-size: 5
      min-idle: 40
      max-active: 80
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        login-username: druid
        login-password: druid

  redis:
    database: 0
    host: 106.75.115.170
    port: 6379
    password: gwk_632697105qq@.redis
    lettuce:
      pool:
        # 最大可用连接数（默认为8，负数表示无限）
        max-active: 300
        # 最大空闲连接数（默认为8，负数表示无限）
        max-idle: 100
        # 最小空闲连接数（默认为0，该值只有为正数才有作用）
        min-idle: 50
        # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
        max-wait: 3000
        time-out: 15000
        shutdown-time-out: 5000

    redisson: # redisson的配置
      address: redis://106.75.115.170:6379
      password: gwk_632697105qq@.redis

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志


sibe:
  compass:
    switchgds: true
    compresstype: GZIP
    #  switchgds所有站点统一 开启或关闭 ,切换gds开关是必须情况原来的redis
    #  switchsite  注意B2C 统一站点和OTA 统一站点一致
    # 1 ） GZIP 的压缩率最高，但是其实 CPU 密集型的，对 CPU 的消耗比其他算法要多，压缩和解压速度也慢 remainning 13.4%  encoding 21MS/s decoding 118MB/s；
    # 2 ） LZO 的压缩率居中，比 GZIP 要低一些，但是压缩和解压速度明显要比 GZIP 快很多，其中解压速度快的更多 remainning 20.5%  encoding 135MS/s decoding 410MB/s；
    # 3 ） Zippy/Snappy 的压缩率最低，而压缩和解压速度要稍微比 LZO 要快一些。remainning 22.2%  encoding 172MS/s decoding 409MB/s
  search:
    #异常查询，如果为true，异步请求GDS， false则同步请求GDS
    async: false

  redis:
    #刷新缓存开关，是否开机刷新缓存
    refresh-switch: true
    #是否将gds数据缓存至redis
    refresh-gds-switch: true
    #是否刷新其它站点数据至redis
    refresh-other-site-switch: false
    #刷新其它站点相关列表配置 OTA平台代码-站点代码 如： CTRIP-CT001,QUNAR-QNPT,CTRIP-XCPT,CTRIP-CT003
    refresh-ota-sites: QUNAR-QNPT,CTRIP-XCPT

  #OTA站点相关
  ota:
    # 加密datakey ## 的Data Key
    data-key: 6784397598743236
    #cid 可以理解为：app key 身份识别
    cid: 6e2b04bf29644892
    #密钥 生单、支付校验接口传输数据须做 AES 加密后进行 BASE64 转码,密钥满足 128 位
    skey: 8784337598743272
    #日志
    logger-path: /log/sibe
    #日志文件是否保存本地
    logger-save-file-flag: true
    #1.没有匹配上政策，或者没有政策录入其他说明， 则返回此信息 Rule Element 其他说明： 注意@@仅仅是区分 直接政策投放，还是手功政策投放
    other-issue-ticket-msg: 只提供国际报销凭证（香港INVOICE）,所有退票改期必须提前48小时申请，否则视为误机,误机后不得退票。退改业务请在工作时间（周一至周五09:00~17:30）联系我们。友情提示：机票须按航班起飞时间顺序使用，否则无法登机。本公司只是机票代理，签证问题请自行确认，保证24小时以内出票。@@
    #other-issue-ticket-msg: 机票说明：1:下单后请及时付款，以免座位被取消；2:机票须按航班起飞时间顺序使用，否则无法登机；3：签证问题请自行确认；4：请务必认真核实姓名，避免填错给您带来的经济损失.@@
    #数据接收方OTA平台站点的缓存时间，单位秒
    ota-site-cache-time: 600
    #共享航班生单延迟响应结果时间：ms
#    order-delayed-time: 5000

  #GDS相关
  gds:
    fuse-time: 20
    # 缓存无效航线（无价格的航线，无效的航线）的失效时间（单位：时）
    #并发幂等性控制
    search-idempotent: true
    invalid-route-survival-time: 168
    aq:
      app-key: test
      contact:
        name: A1IncLtd
        address: FLAT G, 15/F, KINGLAND APARTMENTS, 739 NATHAN ROAD MONGKOK, KOWLOON, HK
        mobile: SZX 86-18948735931-HONG KONG NG CHOW INTERNATIONAL TRAVEL
        ctct: 8618948735931
        email: APE-sxycsh@cywz.cn
    cq:
      app-key: test
      contact:
        name: HONG KONG NG CHOW INTERNATIONAL TRAVEL LTD - WEBSVC
        address: FLAT G, 15/F, KINGLAND APARTMENTS, 739 NATHAN ROAD MONGKOK, KOWLOON, HK
        mobile: 852-31055092
        ctct: 8618948735931
        email: MT.sxycsh@cywz.cn
    nh:
      app-key: test
      contact:
        name: HONG KONG NG CHOW INTERNATIONAL TRAVEL LTD - WEBSVC
        address: FLAT G, 15/F, KINGLAND APARTMENTS, 739 NATHAN ROAD MONGKOK, KOWLOON, HK
        mobile: 852-31055092
        ctct: 8618948735931
        email: MT.sxycsh@cywz.cn
    kjy:
      app-key: test
      contact:
        name: HONG KONG NG CHOW INTERNATIONAL TRAVEL LTD - WEBSVC
        address: FLAT G, 15/F, KINGLAND APARTMENTS, 739 NATHAN ROAD MONGKOK, KOWLOON, HK
        mobile: 852-31055092
        ctct: 8618948735931
        email: MT.sxycsh@cywz.cn




